version: "3.9"

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db

  api:
    build: ./api
    command: npm run dev
    volumes:
      - ./api:/app
    restart: always
    ports:
      - 3001:3001
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/myapp
      - PORT=3001

volumes:
  mongodb:
